# Generated by Django 4.1.5 on 2023-01-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical_Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemical_category', models.CharField(default=None, max_length=200, null=True)),
                ('chemical_name', models.CharField(default=None, max_length=200, null=True)),
                ('value_b', models.CharField(default=None, max_length=200, null=True)),
                ('value_m', models.CharField(default=None, max_length=200, null=True)),
                ('parameter_y', models.CharField(default=None, max_length=200, null=True)),
            ],
            options={
                'db_table': 'chemical_properties',
            },
        ),
    ]
