# Generated by Django 4.1.5 on 2023-01-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rgb_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.AlterField(
            model_name='chemical_properties',
            name='chemical_category',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='chemical_properties',
            name='chemical_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='chemical_properties',
            name='parameter_y',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='chemical_properties',
            name='value_b',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='chemical_properties',
            name='value_m',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
